# Generated by Django 3.1.7 on 2021-02-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
                ('msg_body', models.TextField(blank=True, max_length=500, null=True)),
                ('is_send', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'db_table': 'messages',
            },
        ),
    ]
