# Generated by Django 3.1.7 on 2021-02-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='modified',
            field=models.DateField(null=True),
        ),
    ]
