# Generated by Django 3.1.7 on 2021-02-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_message_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
