# Generated by Django 3.1.7 on 2021-02-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20210222_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='modified',
            field=models.DateField(null=True),
        ),
    ]
